default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") { 'postgres' } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { 'dantito32' } %>
  host: <%= ENV.fetch("DATABASE_HOST") { 'localhost' } %>

development:
  <<: *default
  database: proyecto_arriendos_development

test:
  <<: *default
  database: proyecto_arriendos_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
